# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 700)
        Form.setMinimumSize(QtCore.QSize(700, 700))
        Form.setMaximumSize(QtCore.QSize(700, 700))
        Form.setStyleSheet("QWidget#page{\n"
"    background-image: url(tictactoebackground.jpg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: cover;\n"
"    }\n"
"\n"
"QWidget#page_2{\n"
"    background-image: url(tictactoebackground.jpg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: cover;\n"
"    }\n"
"\n"
"QLabel#titleLabel{\n"
"    \n"
"    font: 75pt \"Impact\";\n"
"    color: rgb(45, 42, 50)\n"
"    \n"
"    }\n"
"\n"
"QLabel#scoreboard{\n"
"    \n"
"    background-color: rgb(237, 255, 113);\n"
"    }\n"
"\n"
"QPushButton#startButton{\n"
"    background-color: rgb(45, 42, 50);\n"
"    }\n"
"\n"
"QspinBox#gp_selector{\n"
"    color: rgb(45, 42, 50);\n"
"    border-width: 3;\n"
"    }\n"
"\n"
"QLineEdit#lineEdit{\n"
"    background-color: rgb(87, 82, 97);\n"
"    border: 2px solid rgb(45, 42, 50);\n"
"    color: #FFF;\n"
"    }\n"
"\n"
"QLineEdit#lineEdit_2{\n"
"    background-color: rgb(87, 82, 97);\n"
"    border: 2px solid rgb(45, 42, 50);\n"
"    color: #FFF;\n"
"    }\n"
"")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 700, 700))
        self.stackedWidget.setMinimumSize(QtCore.QSize(700, 700))
        self.stackedWidget.setMaximumSize(QtCore.QSize(700, 700))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.titleLabel = QtWidgets.QLabel(parent=self.page)
        self.titleLabel.setGeometry(QtCore.QRect(0, 0, 700, 200))
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.startButton = QtWidgets.QPushButton(parent=self.page)
        self.startButton.setGeometry(QtCore.QRect(210, 600, 200, 60))
        self.startButton.setObjectName("startButton")
        self.scoreboard = QtWidgets.QLabel(parent=self.page)
        self.scoreboard.setGeometry(QtCore.QRect(50, 240, 600, 321))
        self.scoreboard.setText("")
        self.scoreboard.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.scoreboard.setObjectName("scoreboard")
        self.gp_selector = QtWidgets.QSpinBox(parent=self.page)
        self.gp_selector.setGeometry(QtCore.QRect(150, 600, 58, 58))
        self.gp_selector.setMinimum(1)
        self.gp_selector.setMaximum(25)
        self.gp_selector.setObjectName("gp_selector")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit.setGeometry(QtCore.QRect(410, 600, 121, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_2.setGeometry(QtCore.QRect(410, 630, 121, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("QPushButton#gridAA{\n"
"    border-width: 0px\n"
"}\n"
"\n"
"QPushButton#mainMenuButton{\n"
"    background-color: rgb(45, 42, 50);\n"
"    font: 75 8pt \"Segoe UI\";\n"
"    font: bold\n"
"}\n"
"\n"
"QLabel#gamereadout{\n"
"    font: 50pt \"Impact\";\n"
"    color: rgb(45, 42, 50);\n"
"}\n"
"\n"
"QLabel#player1readout{\n"
"    background-color: rgb(45, 42, 50);\n"
"    font: 75 8pt \"Segoe UI\";\n"
"    font: bold\n"
"}\n"
"\n"
"QLabel#player2readout{\n"
"    background-color: rgb(45, 42, 50);\n"
"    font: 75 8pt \"Segoe UI\";\n"
"    font: bold\n"
"}")
        self.page_2.setObjectName("page_2")
        self.gamereadout = QtWidgets.QLabel(parent=self.page_2)
        self.gamereadout.setGeometry(QtCore.QRect(0, 0, 700, 150))
        self.gamereadout.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gamereadout.setObjectName("gamereadout")
        self.mainMenuButton = QtWidgets.QPushButton(parent=self.page_2)
        self.mainMenuButton.setGeometry(QtCore.QRect(275, 630, 150, 60))
        self.mainMenuButton.setObjectName("mainMenuButton")
        self.frame = QtWidgets.QFrame(parent=self.page_2)
        self.frame.setGeometry(QtCore.QRect(175, 210, 350, 350))
        self.frame.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 316, 323))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gbutton21 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.gbutton21.setMinimumSize(QtCore.QSize(100, 100))
        self.gbutton21.setMaximumSize(QtCore.QSize(100, 100))
        self.gbutton21.setText("")
        self.gbutton21.setObjectName("gbutton21")
        self.gridLayout.addWidget(self.gbutton21, 2, 1, 1, 1)
        self.gbutton22 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.gbutton22.setMinimumSize(QtCore.QSize(100, 100))
        self.gbutton22.setMaximumSize(QtCore.QSize(100, 100))
        self.gbutton22.setText("")
        self.gbutton22.setObjectName("gbutton22")
        self.gridLayout.addWidget(self.gbutton22, 2, 2, 1, 1)
        self.gbutton20 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.gbutton20.setMinimumSize(QtCore.QSize(100, 100))
        self.gbutton20.setMaximumSize(QtCore.QSize(100, 100))
        self.gbutton20.setText("")
        self.gbutton20.setObjectName("gbutton20")
        self.gridLayout.addWidget(self.gbutton20, 2, 0, 1, 1)
        self.gbutton12 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.gbutton12.setMinimumSize(QtCore.QSize(100, 100))
        self.gbutton12.setMaximumSize(QtCore.QSize(100, 100))
        self.gbutton12.setText("")
        self.gbutton12.setObjectName("gbutton12")
        self.gridLayout.addWidget(self.gbutton12, 1, 2, 1, 1)
        self.gbutton11 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.gbutton11.setMinimumSize(QtCore.QSize(100, 100))
        self.gbutton11.setMaximumSize(QtCore.QSize(100, 100))
        self.gbutton11.setText("")
        self.gbutton11.setObjectName("gbutton11")
        self.gridLayout.addWidget(self.gbutton11, 1, 1, 1, 1)
        self.gbutton10 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.gbutton10.setMinimumSize(QtCore.QSize(100, 100))
        self.gbutton10.setMaximumSize(QtCore.QSize(100, 100))
        self.gbutton10.setText("")
        self.gbutton10.setObjectName("gbutton10")
        self.gridLayout.addWidget(self.gbutton10, 1, 0, 1, 1)
        self.gbutton00 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.gbutton00.setMinimumSize(QtCore.QSize(100, 100))
        self.gbutton00.setMaximumSize(QtCore.QSize(100, 100))
        self.gbutton00.setText("")
        self.gbutton00.setObjectName("gbutton00")
        self.gridLayout.addWidget(self.gbutton00, 0, 0, 1, 1)
        self.gbutton02 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.gbutton02.setMinimumSize(QtCore.QSize(100, 100))
        self.gbutton02.setMaximumSize(QtCore.QSize(100, 100))
        self.gbutton02.setText("")
        self.gbutton02.setObjectName("gbutton02")
        self.gridLayout.addWidget(self.gbutton02, 0, 2, 1, 1)
        self.gbutton01 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.gbutton01.setMinimumSize(QtCore.QSize(100, 100))
        self.gbutton01.setMaximumSize(QtCore.QSize(100, 100))
        self.gbutton01.setText("")
        self.gbutton01.setObjectName("gbutton01")
        self.gridLayout.addWidget(self.gbutton01, 0, 1, 1, 1)
        self.player1readout = QtWidgets.QLabel(parent=self.page_2)
        self.player1readout.setGeometry(QtCore.QRect(10, 590, 100, 100))
        self.player1readout.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.player1readout.setObjectName("player1readout")
        self.player2readout = QtWidgets.QLabel(parent=self.page_2)
        self.player2readout.setGeometry(QtCore.QRect(590, 590, 100, 100))
        self.player2readout.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.player2readout.setObjectName("player2readout")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titleLabel.setText(_translate("Form", "TIC TAC TOE"))
        self.startButton.setText(_translate("Form", "Start Game"))
        self.gamereadout.setText(_translate("Form", "GAME SCREEN"))
        self.mainMenuButton.setText(_translate("Form", "Main Menu"))
        self.player1readout.setText(_translate("Form", "player1name\n"
"symbol\n"
"points"))
        self.player2readout.setText(_translate("Form", "player2name\n"
"symbol\n"
"points"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
